### ISSUE TITLE
Air Drive APP 在IOS 8 閃退

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-drive#1]
Hi, your PQI Air Drive+ app for iOS seems to be very incompatible with iOS 8. After i've upgraded my system to iOS 8, a lot of songs get unstable, and they can't be played. They also cause the program to crash and go back to Home screen.
Please inform me what can be done to change this, and whether your company's fixing this.
Thank you.

下列是與客戶澄清的狀況：
1. PQI: Please kindly remove those songs and try again. Is the problem remained?
Customer Feedback: I've tried removing them, and then putting it in again, they don't work still. Also, as I explained, some songs work, some don't. For example, I have 3 folders: A, B & C. Folder A works, Folder B doesn't work, but Folder C songs work.
1. PQI: Please kindly help to check those songs in your computer, could they be played?
   Customer Feedback: They all work in my computer, I've tested the original .mp3 file, and also I plugged the Air Drive into the computer, I can play the songs from inside the Air Drive on the computer as well, so it's just the program I think.

**Comment by yiming330** [comment]
Can you check with the customer which iOS device he/she was using? (ex: iPhone4, 4S, 5, 5S, and iOS version: 8.1?)

**Comment by PQI-APP** [comment]
the user was using i-pad mini2
以下為客戶回覆:
The music running issues came up when I upgraded from iOS 7.2 to iOS 8.1. I'm using an iPad Mini with retina display (iPad mini 2).

**Comment by PQI-APP** [comment]
APP 評論上一直有反應閃退問題

![2014-11-06 11 09 45](https://cloud.githubusercontent.com/assets/8001211/4930320/9c75167a-6562-11e4-968b-72676eb4958b.png)

**Comment by yiming330** [comment]
We have found a bug related to mp3 issue, and fixed it. However, as we do not have the same files and environment that the user used, so we are unable to make sure this is the right fix. I recommend that we submit a new version to Apple now as it will take more than 1 week to approve. And meanwhile, we will continue to track down more issues.

**Comment by PQI-APP** [comment]
hi
do you have any update about this issue?

## we have still received user's claim about this:

## Hi, i am a fan of your products and i thin the PQI air drive is brilliant hardware. The only thing that lets it down is the app which crashes more often than not when trying to play music, please could you guys update the app for iOS 8 so that the hardware can be as good as it should be?

**Comment by yiming330** [comment]
這個問題已經上次已經修復, 但是仍然等待FAE這邊測試完成, 我們可以submit到apple更新版本

**Comment by yiming330** [comment]
The issue has been fixed along with the new version released.
